const Data = [
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag:
      "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/twitter/281/flag-india_1f1ee-1f1f3.png",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
    maintainer_photo: "https://avatars.githubusercontent.com/u/30292727?v=4",
  },
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag:
      "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/twitter/281/flag-india_1f1ee-1f1f3.png",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
    maintainer_photo: "https://avatars.githubusercontent.com/u/30292727?v=4",
  },
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag:
      "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/twitter/281/flag-india_1f1ee-1f1f3.png",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
    maintainer_photo: "https://avatars.githubusercontent.com/u/30292727?v=4",
  },
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag:
      "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/twitter/281/flag-india_1f1ee-1f1f3.png",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
    maintainer_photo: "https://avatars.githubusercontent.com/u/30292727?v=4",
  },
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag:
      "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/twitter/281/flag-india_1f1ee-1f1f3.png",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
    maintainer_photo: "https://avatars.githubusercontent.com/u/30292727?v=4",
  },
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag:
      "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/twitter/281/flag-india_1f1ee-1f1f3.png",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
    maintainer_photo: "https://avatars.githubusercontent.com/u/30292727?v=4",
  },
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag:
      "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/twitter/281/flag-india_1f1ee-1f1f3.png",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
    maintainer_photo: "https://avatars.githubusercontent.com/u/30292727?v=4",
  },
];
export default Data;
