const Data = [
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag: "flag_link",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
  },
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag: "flag_link",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
  },
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag: "flag_link",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
  },
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag: "flag_link",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
  },
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag: "flag_link",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
  },
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: [
      "Asus Zenfone Max Pro M1",
      "new mobile",
      "new mobile",
      "new mobile",
      "new mobile",
    ],
    country: "INDIA",
    country_flag: "flag_link",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
  },
  {
    maintainer_name: "LordShen",
    maintainer_xda: "",
    maintainer_github: "https://github.com/LordShen/",
    devices_mantaining: ["Asus Zenfone Max Pro M1"],
    country: "INDIA",
    country_flag: "flag_link",
    more_info: "degenerate weeb",
    telegram_link: "",
    github_link: "",
  },
];
export default Data;
